version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PORT_DB}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    restart: always
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb

  backend:
    image: php:8.2-apache
    container_name: php-backend1
    restart: always
    ports:
      - "${PORT_BACKEND}:80"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: bash -c "docker-php-ext-install pdo pdo_mysql && a2enmod rewrite && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && composer install && apache2-foreground"
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  mariadb_data:
